name: Static analysis for Java
permissions: {}
on: [ push, pull_request ]

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  ALLOWED_ENDPOINTS: >
    api.adoptium.net:443
    api.foojay.io:443
    api.github.com:443
    caffeine.gradle-enterprise.cloud:443
    downloads.gradle.org:443
    downloads.gradle-dn.com:443
    github.com:443
    jcenter.bintray.com:443
    objects.githubusercontent.com:443
    plugins.gradle.org:443
    plugins-artifacts.gradle.org:443
    repo.maven.apache.org:443
    repo1.maven.org:443
    services.gradle.org:443

jobs:
  ecj:
    name: Eclipse Compiler for Java
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JAVA_VERSION: 24
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: ${{ env.ALLOWED_ENDPOINTS }}
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: ECJ
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: ecjJavaPoet ecjMain ecjCodeGen ecjJmh ecjTest ecjJcstress

  forbidden-apis:
    name: Forbidden APIs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JAVA_VERSION: 24
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: ${{ env.ALLOWED_ENDPOINTS }}
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Forbidden Apis
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          arguments: forbiddenApis -PforbiddenApis
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  pmd:
    name: PMD
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JAVA_VERSION: 24
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: ${{ env.ALLOWED_ENDPOINTS }}
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Pmd
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: pmdJavaPoet pmdMain pmdCodeGen pmdJmh pmdTest pmdJcstress -Ppmd
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          retention-days: 1
          name: pmd-reports
          path: "**/build/reports/pmd/*.html"

  revapi:
    name: Revapi
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JAVA_VERSION: 24
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: ${{ env.ALLOWED_ENDPOINTS }}
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Revapi
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          arguments: revapi -Prevapi --no-configuration-cache
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  spotbugs:
    name: Spotbugs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JAVA_VERSION: 24
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: ${{ env.ALLOWED_ENDPOINTS }}
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Spotbugs
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: >
            spotbugsJavaPoet spotbugsMain spotbugsCodeGen
            spotbugsJmh spotbugsTest spotbugsJcstress -Pspotbugs
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          retention-days: 1
          name: spotbugs-reports
          path: "**/build/reports/spotbugs/*.html"
