name: JCStress
permissions: {}
on:
  schedule:
    - cron: '0 0 * * 1'

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  ALLOWED_ENDPOINTS: >
    api.adoptium.net:443
    api.foojay.io:443
    api.github.com:443
    caffeine.gradle-enterprise.cloud:443
    downloads.gradle.org:443
    downloads.gradle-dn.com:443
    github.com:443
    jcenter.bintray.com:443
    objects.githubusercontent.com:443
    plugins.gradle.org:443
    plugins-artifacts.gradle.org:443
    repo.maven.apache.org:443
    repo1.maven.org:443
    services.gradle.org:443

jobs:
  jcstress:
    name: JCStress
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        java: [ 11, 24, 25-ea ]
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    env:
      JAVA_VERSION: ${{ matrix.java }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          allowed-endpoints: ${{ env.ALLOWED_ENDPOINTS }}
          disable-sudo-and-containers: true
          egress-policy: block
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: JCStress
        uses: ./.github/actions/run-gradle
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          java: ${{ env.JAVA_VERSION }}
          arguments: jcstress
